plugins:
  - jekyll-sitemap
  
kramdown:
  hard_wrap: true

collections:
  authors:
    output: true
    permalink: "/auteurs/:name"
  tags:
    output: true
    permalink: "/tags/:name"
  posts:
    output: true
    permalink: "/:categories/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "articles"
      note: false
  -
    scope:
      path: "nouvelles"
      type: "pages"
    values:
      layout: "short-story"
      scroll: true